-- Displayed Design 1 events, copied verbatim from src/data/events.ts.
-- Capacities are NOT defined by the live preview; zero prevents inventing inventory.
-- Assign an authenticated organiser and real capacities before enabling sales.
begin;
insert into public.website_organisations(id,name) values('e4510000-0000-4000-8000-000000000001','Easy Tickets Namibia') on conflict(id) do nothing;
insert into public.website_events(id,organisation_id,title,starts_at,published,payload) values(1,'e4510000-0000-4000-8000-000000000001','Windhoek Cultural Festival','2026-10-17T14:00:00+02:00'::timestamptz,true,'{"id":1,"title":"Windhoek Cultural Festival","date":"OCT 17","fullDate":"October 17, 2026","startsAt":"2026/10/17 14:00","price":150,"img":"/images/design1/evt1.png","location":"Independence Stadium, Windhoek","time":"14:00 – 22:00","category":"Culture","description":"Namibian music, dance, craft and food come together at Independence Stadium. See the day’s artists, browse local makers and taste dishes from across the country. Suitable for families.","tiers":[{"id":"standard","name":"Standard","price":150,"perks":["General admission","Access to main stage"],"capacity":0},{"id":"premium","name":"Premium","price":350,"perks":["Priority entry","Reserved seating","1 complimentary drink"],"capacity":0},{"id":"vip","name":"VIP","price":600,"perks":["Fast-track entry","VIP lounge access","Open bar","Meet & greet"],"capacity":0}]}'::jsonb) on conflict(id) do nothing;
insert into public.website_events(id,organisation_id,title,starts_at,published,payload) values(2,'e4510000-0000-4000-8000-000000000001','Desert Dune Music Fest','2026-11-14T16:00:00+02:00'::timestamptz,true,'{"id":2,"title":"Desert Dune Music Fest","date":"NOV 14","fullDate":"November 14, 2026","startsAt":"2026/11/14 16:00","price":250,"img":"/images/design1/evt2.png","location":"Swakopmund Dunes","time":"16:00 – 02:00","category":"Music","description":"Three stages of electronic music in the Swakopmund dunes, with Namibian and visiting DJs, art installations and food vendors. Gates open at 16:00.","tiers":[{"id":"standard","name":"Standard","price":250,"perks":["General admission","Access to main stage"],"capacity":0},{"id":"premium","name":"Premium","price":350,"perks":["Priority entry","Reserved seating","1 complimentary drink"],"capacity":0},{"id":"vip","name":"VIP","price":600,"perks":["Fast-track entry","VIP lounge access","Open bar","Meet & greet"],"capacity":0}]}'::jsonb) on conflict(id) do nothing;
insert into public.website_events(id,organisation_id,title,starts_at,published,payload) values(3,'e4510000-0000-4000-8000-000000000001','Namibian Food & Wine Expo','2026-12-06T10:00:00+02:00'::timestamptz,true,'{"id":3,"title":"Namibian Food & Wine Expo","date":"DEC 06","fullDate":"December 6, 2026","startsAt":"2026/12/06 10:00","price":100,"img":"/images/design1/evt3.png","location":"Zoo Park, Windhoek","time":"10:00 – 18:00","category":"Food","description":"Meet Namibian chefs, winemakers and independent producers at Zoo Park. The programme includes tastings, cooking demonstrations and practical workshops.","tiers":[{"id":"standard","name":"Standard","price":100,"perks":["General admission","Access to main stage"],"capacity":0},{"id":"premium","name":"Premium","price":350,"perks":["Priority entry","Reserved seating","1 complimentary drink"],"capacity":0},{"id":"vip","name":"VIP","price":600,"perks":["Fast-track entry","VIP lounge access","Open bar","Meet & greet"],"capacity":0}]}'::jsonb) on conflict(id) do nothing;
insert into public.website_events(id,organisation_id,title,starts_at,published,payload) values(4,'e4510000-0000-4000-8000-000000000001','Etosha Trail Marathon','2027-01-17T06:00:00+02:00'::timestamptz,true,'{"id":4,"title":"Etosha Trail Marathon","date":"JAN 17","fullDate":"January 17, 2027","startsAt":"2027/01/17 06:00","price":200,"img":"/images/design1/evt4.png","location":"Etosha National Park","time":"06:00 – 14:00","category":"Sport","description":"Choose a 10 km, 21 km or full-marathon trail through Etosha’s landscape. Entry includes the post-race braai, live music and awards.","tiers":[{"id":"standard","name":"Standard","price":200,"perks":["General admission","Access to main stage"],"capacity":0},{"id":"premium","name":"Premium","price":350,"perks":["Priority entry","Reserved seating","1 complimentary drink"],"capacity":0},{"id":"vip","name":"VIP","price":600,"perks":["Fast-track entry","VIP lounge access","Open bar","Meet & greet"],"capacity":0}]}'::jsonb) on conflict(id) do nothing;
insert into public.website_events(id,organisation_id,title,starts_at,published,payload) values(5,'e4510000-0000-4000-8000-000000000001','Coastal Jazz Weekend','2027-02-13T17:00:00+02:00'::timestamptz,true,'{"id":5,"title":"Coastal Jazz Weekend","date":"FEB 13","fullDate":"February 13–14, 2027","startsAt":"2027/02/13 17:00","price":180,"img":"/images/design1/evt1.png","location":"Walvis Bay Waterfront","time":"17:00 – 23:00","category":"Music","description":"Two evenings of jazz, Afro-fusion and soul at the Walvis Bay Waterfront, with Namibian and visiting artists, seafood vendors and sunset sets.","tiers":[{"id":"standard","name":"Standard","price":180,"perks":["General admission","Access to main stage"],"capacity":0},{"id":"premium","name":"Premium","price":350,"perks":["Priority entry","Reserved seating","1 complimentary drink"],"capacity":0},{"id":"vip","name":"VIP","price":600,"perks":["Fast-track entry","VIP lounge access","Open bar","Meet & greet"],"capacity":0}]}'::jsonb) on conflict(id) do nothing;
insert into public.website_events(id,organisation_id,title,starts_at,published,payload) values(6,'e4510000-0000-4000-8000-000000000001','Windhoek Comedy Night','2027-02-26T19:00:00+02:00'::timestamptz,true,'{"id":6,"title":"Windhoek Comedy Night","date":"FEB 26","fullDate":"February 26, 2027","startsAt":"2027/02/26 19:00","price":120,"img":"/images/design1/evt2.png","location":"National Theatre, Windhoek","time":"19:00 – 22:30","category":"Entertainment","description":"Namibian comedians share the National Theatre stage with two visiting headliners. Doors open at 19:00; bar and food service are available.","tiers":[{"id":"standard","name":"Standard","price":120,"perks":["General admission","Access to main stage"],"capacity":0},{"id":"premium","name":"Premium","price":350,"perks":["Priority entry","Reserved seating","1 complimentary drink"],"capacity":0},{"id":"vip","name":"VIP","price":600,"perks":["Fast-track entry","VIP lounge access","Open bar","Meet & greet"],"capacity":0}]}'::jsonb) on conflict(id) do nothing;
-- Preserve the migration's 1000+ range for new organiser-created events.
select setval('public.website_events_id_seq',greatest(1000,(select coalesce(max(id),0)+1 from public.website_events),(select last_value+case when is_called then 1 else 0 end from public.website_events_id_seq)),false);
commit;
