"use client";
import Link from "next/link";
import { useState,useEffect } from "react";
import { UserRound, Ticket, Heart, ArrowRight, Loader2 } from "lucide-react";
import { useAccount } from "./AccountProvider";
import { browserSupabase } from "@/lib/supabase/client";
import type { EventItem } from "@/data/events";
import EventCard from "./EventCard";
type Booking = {id:string;ref:string;event_name:string;event_date:string;status:string;amount:number|string;currency:string;receiptUrl:string|null;items:{name:string;qty:number}[]};
type Profile = {full_name:string;phone:string;city:string};
export default function AccountPanel({ section,events }: { section:string;events:EventItem[] }) {
  const {user,loading,configured} = useAccount(); const [profile,setProfile] = useState<Profile>({full_name:"",phone:"",city:""}); const [orders,setOrders] = useState<Booking[]>([]); const [saved,setSaved] = useState<number[]>([]); const [busy,setBusy] = useState(false); const [fetching,setFetching] = useState(true); const [error,setError] = useState(""); const [message,setMessage] = useState("");
  useEffect(() => {
    if(!user) return; let active = true;
    const endpoint = section === "saved" ? "saved" : section === "tickets" ? "tickets" : "profile";
    fetch(`/api/account/${endpoint}`,{cache:"no-store"}).then(async r => { const body=await r.json(); if(!r.ok) throw new Error(body.error); if(active) { if(endpoint==="profile") setProfile(body.profile); if(endpoint==="saved") setSaved(body.ids); if(endpoint==="tickets") setOrders(body.orders); } }).catch(e => {if(active) setError(e.message);}).finally(() => {if(active) setFetching(false);});
    return () => {active=false;};
  },[user,section]);
  async function save(e:React.FormEvent<HTMLFormElement>) { e.preventDefault();setBusy(true);setError("");setMessage("");try {const r=await fetch("/api/account/profile",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:profile.full_name,phone:profile.phone,city:profile.city})});const body=await r.json();if(!r.ok)throw new Error(body.error);setMessage("Your profile is saved.");}catch(e){setError((e as Error).message);}finally{setBusy(false);} }
  async function logout(){ await browserSupabase().auth.signOut();window.location.assign("/"); }
  if(loading) return <div className="empty-state"><Loader2 size={26} className="spin"/><p>Loading your account…</p></div>;
  if(!user) return <div className="empty-state"><Ticket size={34}/><h2>Your plans, all together.</h2><p>{configured ? "Sign in to see your tickets, saved events and profile." : "Account services are awaiting the Easy Tickets connection."}</p><Link className="button primary" href={`/auth/sign-in?next=${encodeURIComponent(section==="profile" ? "/account" : `/account/${section}`)}`}>Sign in <ArrowRight size={17}/></Link><Link className="text-link" href="/auth/sign-up">Create an account</Link></div>;
  return <div className="account-grid"><nav className="account-nav" aria-label="Account navigation">{[["profile","My profile",UserRound],["tickets","My tickets",Ticket],["saved","Saved events",Heart]].map(([key,label,Icon]) => {const Component=Icon as typeof UserRound;return <Link key={String(key)} className={section===key ? "active" : ""} href={key==="profile" ? "/account" : `/account/${key}`}><Component size={17}/>{label as string}</Link>;})}<button onClick={logout}>Sign out</button></nav><section className="account-main" key={section}><h2>{section==="profile" ? "My profile" : section==="tickets" ? "My tickets" : "Saved events"}</h2><p className="muted">{section==="profile" ? user.email : section==="tickets" ? "Bookings made while signed in appear here." : "Keep a shortlist for your next night out."}</p>{error && <p className="form-error" role="alert">{error}</p>}{fetching && <p className="muted">Loading…</p>}{section==="profile" && !fetching && <form className="form-stack" onSubmit={save}><label>Full name<input value={profile.full_name} onChange={e=>setProfile({...profile,full_name:e.target.value})} minLength={2} maxLength={100} required autoComplete="name"/></label><label>Phone number<input type="tel" value={profile.phone || ""} onChange={e=>setProfile({...profile,phone:e.target.value})} maxLength={30} autoComplete="tel"/></label><label>City<input value={profile.city || ""} onChange={e=>setProfile({...profile,city:e.target.value})} maxLength={60} autoComplete="address-level2"/></label>{message && <p className="form-success" role="status">{message}</p>}<button className="button primary" disabled={busy}>{busy ? "Saving…" : "Save changes"}</button><Link href="/auth/forgot-password" className="text-link">Reset your password</Link></form>}{section==="tickets" && !fetching && !error && (orders.length ? orders.map(o=><article className="order-card" key={o.id}><div className="order-card-top"><span>{o.ref}</span><span className={`status-tag status-${o.status}`}>{o.status}</span></div><h3>{o.event_name}</h3><p>{o.items.map(i=>`${i.qty} × ${i.name}`).join(" · ")} · {o.currency} {Number(o.amount).toFixed(2)}</p>{o.receiptUrl && <Link className="button secondary" href={o.receiptUrl}>Open tickets <ArrowRight size={16}/></Link>}</article>) : <div className="empty-state"><Ticket size={30}/><h2>Your next plan is waiting.</h2><p>Bookings made while signed in will appear here.</p><Link className="button primary" href="/events">Find an event</Link></div>)}{section==="saved" && !fetching && !error && (saved.length ? <div className="event-grid">{events.filter(e=>saved.includes(e.id)).map(e=><EventCard key={e.id} event={e} saved/>)}</div> : <div className="empty-state"><Heart size={30}/><h2>Start your shortlist.</h2><p>Tap the heart on an event to save it here.</p><Link className="button primary" href="/events">Browse events</Link></div>)}</section></div>;
}
