"use client";
import { useState } from "react";
import Link from "next/link";
import { Minus, Plus, ArrowRight, LockKeyhole, Loader2 } from "lucide-react";
import type { EventItem } from "@/data/events";
import { MAX_TICKETS_PER_ORDER, MAX_TICKETS_PER_TIER } from "@/data/events";
import { useAccount } from "./AccountProvider";
import PaymentHandoff from "./PaymentHandoff";
export default function BookingForm({ event, preview }: { event: EventItem; preview: boolean }) {
  const { user } = useAccount(); const [quantities, setQuantities] = useState<number[]>(event.tiers.map((t,i) => i === 0 && (t.available ?? t.capacity ?? 1)>0 ? 1 : 0)); const [step,setStep] = useState(1); const [busy,setBusy] = useState(false); const [error,setError] = useState("");
  const total = event.tiers.reduce((sum,t,i) => sum+t.price*quantities[i],0); const count = quantities.reduce((a,b) => a+b,0);
  function change(i: number, delta: number) { setQuantities(q => q.map((n,j) => j === i ? Math.max(0,Math.min(Math.min(MAX_TICKETS_PER_TIER,event.tiers[i].available ?? event.tiers[i].capacity ?? MAX_TICKETS_PER_TIER),n+delta)) : n)); }
  async function checkout(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault(); setBusy(true); setError(""); const fd = new FormData(e.currentTarget);
    try { const r = await fetch("/api/checkout", { method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify({ eventId:event.id, items:event.tiers.map((t,i) => ({ tier:t.id,qty:quantities[i] })), name:fd.get("name"),email:fd.get("email"),phone:fd.get("phone") }) }); const body = await r.json(); if(!r.ok || !body.url) throw new Error(body.error || "We couldn’t start your payment. Please try again."); window.location.assign(body.url); } catch(e) { setError((e as Error).message); setBusy(false); }
  }
  return <aside className="booking-panel" id="book">{busy && <PaymentHandoff/>}<div className="booking-heading"><p className="eyebrow">BOOK TICKETS</p><h2>{step===1 ? "Choose tickets" : "Contact details"}</h2><span>0{step} / 02</span></div>
    {preview && <p className="inline-preview">Preview tickets · Payments unavailable</p>}
    {step===1 ? <div>{event.tiers.map((tier,i) => <div className="ticket-tier" key={tier.id}><div><h3>{tier.name}</h3><p>{tier.perks.slice(0,2).join(" · ")}</p><strong>N${tier.price}</strong></div><div className="quantity-picker"><button className="icon-button" onClick={() => change(i,-1)} aria-label={`Remove ${tier.name} ticket`} disabled={!quantities[i]}><Minus size={15}/></button><span aria-live="polite">{quantities[i]}</span><button className="icon-button" onClick={() => change(i,1)} aria-label={`Add ${tier.name} ticket`} disabled={quantities[i]>=Math.min(MAX_TICKETS_PER_TIER,tier.available ?? tier.capacity ?? MAX_TICKETS_PER_TIER) || count>=MAX_TICKETS_PER_ORDER}><Plus size={15}/></button></div></div>)}<div className="booking-total"><span>{count} {count===1 ? "ticket" : "tickets"}</span><strong>N${total}</strong></div><button className="button primary full" disabled={!count || count>MAX_TICKETS_PER_ORDER} onClick={() => setStep(2)}>Continue <ArrowRight size={18}/></button></div> : <form onSubmit={checkout} className="form-stack"><p className="muted">{user ? "Your booking will appear in My tickets." : <>Book as a guest, or <Link href={`/auth/sign-in?next=/events/${event.id}`}>sign in</Link> to keep it in your account.</>}</p><label>Full name<input name="name" autoComplete="name" required minLength={2} maxLength={100} defaultValue={user?.user_metadata?.full_name || ""} /></label><label>Email address<input name="email" type="email" autoComplete="email" required maxLength={254} defaultValue={user?.email || ""}/></label><label>Phone number<input name="phone" type="tel" autoComplete="tel" placeholder="+264" required minLength={7} maxLength={30}/></label><div className="booking-total"><span>{count} {count===1 ? "ticket" : "tickets"}</span><strong>N${total}</strong></div>{error && <p className="form-error" role="alert">{error}</p>}<button className="button primary full" disabled={busy || preview}>{busy ? <><Loader2 className="spin" size={18}/>Connecting to DPO…</> : <>Pay N${total} with DPO <ArrowRight size={18}/></>}</button><button type="button" className="button secondary full" onClick={() => setStep(1)} disabled={busy}>Back to tickets</button></form>}
    <p className="secure-note"><LockKeyhole size={13}/> Card details are entered on DPO’s secure checkout</p><p className="booking-help">Need help? <Link href="/help">Visit the help centre</Link></p>
  </aside>;
}
