"use client";
import { useState,useEffect,useRef } from "react";
import Link from "next/link";
import { BrowserQRCodeReader,type IScannerControls } from "@zxing/browser";
import { useAccount } from "./AccountProvider";
export default function CheckInPanel(){
  const {user,configured,loading}=useAccount();const [events,setEvents]=useState<{id:number;title:string}[]>([]);const [eventId,setEventId]=useState("");const [credential,setCredential]=useState("");const [message,setMessage]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false);const [camera,setCamera]=useState(false);const video=useRef<HTMLVideoElement>(null);const controls=useRef<IScannerControls|null>(null);
  useEffect(()=>{if(!user)return;fetch("/api/check-in").then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.error);setEvents(b.events);if(b.events.length===1)setEventId(String(b.events[0].id));}).catch(e=>setError(e.message));},[user]);
  useEffect(()=>()=>{controls.current?.stop();},[]);
  async function start(){setError("");setCamera(true);try{if(!video.current)throw new Error("Camera unavailable.");const reader=new BrowserQRCodeReader();controls.current=await reader.decodeFromVideoDevice(undefined,video.current,(result,_error,scannerControls)=>{if(result){setCredential(result.getText());scannerControls.stop();setCamera(false);setMessage("Code read. Check the selected event, then admit the ticket.");}});}catch{setCamera(false);setError("Camera unavailable. Allow camera access, or paste the ticket code below.");}}
  async function admit(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");setMessage("");try{const r=await fetch("/api/check-in",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({credential,eventId:Number(eventId)})});const b=await r.json();if(!r.ok||!b.ok)throw new Error(b.error || "Ticket not valid for this event.");setMessage(`Admitted: ${b.holder} · ${b.tier}`);setCredential("");}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  if(loading)return <p>Loading…</p>;
  if(!user)return <div className="empty-state"><h2>Staff access only</h2><p>{configured?"Sign in with an account assigned to this event.":"Check-in services are awaiting the Easy Tickets connection."}</p><Link className="button primary" href="/auth/sign-in?next=/check-in">Sign in</Link></div>;
  return <div className="auth-card"><h2>Event check-in</h2><p className="muted">Select your assigned event before scanning.</p><form className="form-stack" onSubmit={admit}><label>Event<select required value={eventId} onChange={e=>{controls.current?.stop();setCamera(false);setCredential("");setMessage("");setEventId(e.target.value);}}><option value="">Choose event</option>{events.map(e=><option key={e.id} value={e.id}>{e.title}</option>)}</select></label><video ref={video} hidden={!camera} style={{width:"100%"}} muted playsInline/><button type="button" className="button secondary" disabled={!eventId||busy||camera} onClick={start}>Scan QR with camera</button>{camera && <button type="button" className="button secondary" onClick={()=>{controls.current?.stop();setCamera(false);}}>Stop camera</button>}<label>Ticket code<textarea required value={credential} onChange={e=>setCredential(e.target.value)} placeholder="Scan a QR code, or paste the ET1 ticket code." rows={3}/></label>{error&&<p className="form-error" role="alert">{error}</p>}{message&&<p className="form-success" role="status">{message}</p>}<button className="button primary" disabled={!eventId||busy||!credential}>{busy?"Checking…":"Check ticket & admit"}</button></form>{!events.length&&<p className="inline-preview">No event assignments. Ask your event manager to add your account.</p>}</div>;
}
