import Link from "next/link";
import { ArrowRight, ArrowUpRight, Music2, Drama, Trophy, Utensils, MapPin, Ticket } from "lucide-react";
import type { EventItem } from "@/data/events";
import PageFrame from "./PageFrame";
import SearchForm from "./SearchForm";
import EventCard from "./EventCard";
const categories = [{ name:"Music", label:"Live music", icon:Music2, color:"blue" }, { name:"Culture", label:"Arts & culture", icon:Drama, color:"orange" }, { name:"Sport", label:"Sport", icon:Trophy, color:"green" }, { name:"Food", label:"Food & drink", icon:Utensils, color:"purple" }];
export default function HomePage({ events, preview }: { events: EventItem[]; preview: boolean }) {
  const featured = events.find(e => e.category === "Music") ?? events[0];
  return <PageFrame><main id="main">{preview && <div className="preview-note">Design preview · Example events and prices</div>}
    <section className="wrap home-intro"><div className="intro-heading"><div><p className="eyebrow">LIVE A LITTLE.</p><h1>Your next night out.<br /><span>Starts here.</span></h1></div><p>Live music, big weekends and plans worth making.<br className="desktop-break" /> Find what’s happening in Namibia.</p></div><SearchForm /></section>
    {featured && <section className="wrap featured-section" aria-label="Featured event"><div className="feature-card"><img className="feature-photo" src={preview ? "/images/design1/hero.png" : featured.img} alt={featured.title} fetchPriority="high" /><div className="feature-shade" /><div className="feature-top"><span className="feature-badge">IN THE SPOTLIGHT</span><span>01 / 01</span></div><div className="feature-content"><div><p className="feature-kicker">{featured.fullDate} <span>·</span> {featured.location}</p><h2>{featured.title}</h2><p>Make a weekend of it.</p></div><Link href={`/events/${featured.id}`} className="button white">Explore the event <ArrowUpRight size={19} /></Link></div></div></section>}
    <section className="wrap category-section" aria-label="Explore categories"><span className="eyebrow">FIND YOUR THING</span><div className="category-grid">{categories.map(c => <Link key={c.name} href={`/events?category=${c.name}`}><span className={`category-icon ${c.color}`}><c.icon size={22} /></span><span>{c.label}</span><ArrowUpRight size={18} /></Link>)}</div></section>
    <section className="wrap home-events"><div className="section-heading"><div><p className="eyebrow">ON THE CALENDAR</p><h2>Something to look forward to.</h2></div><Link className="text-link" href="/events">Browse all events <ArrowRight size={18} /></Link></div><div className="event-grid">{events.slice(0,4).map(e => <EventCard key={e.id} event={e} />)}</div>{!events.length && <div className="empty-state"><h3>The calendar is coming together.</h3><p>Check back for upcoming events.</p></div>}</section>
    <section className="city-section"><div className="wrap"><div className="section-heading"><div><p className="eyebrow">CLOSER TO HOME</p><h2>Where are we going?</h2></div><span className="muted">A good plan is never far away.</span></div><div className="city-grid">{["Windhoek","Swakopmund","Walvis Bay"].map((city,i) => <Link href={`/events?city=${encodeURIComponent(city)}`} key={city}><span className="city-number">0{i+1}</span><MapPin size={20} /><h3>{city}</h3><span>Explore events <ArrowUpRight size={16} /></span></Link>)}</div></div></section>
    <section className="wrap account-banner"><span className="account-banner-icon"><Ticket size={30} /></span><div><p className="eyebrow">ALL YOUR PLANS. ONE PLACE.</p><h2>Keep your tickets close.</h2><p>Save events you love and find your bookings in your account.</p></div><Link href="/auth/sign-up" className="button primary">Create an account <ArrowRight size={18} /></Link></section>
  </main></PageFrame>;
}
