import Link from "next/link";
import { ArrowRight, ArrowUpRight, Music2, Drama, Trophy, Utensils, MapPin, Ticket } from "lucide-react";
import type { EventItem } from "@/data/events";
import PageFrame from "./PageFrame";
import SearchForm from "./SearchForm";
import EventCard from "./EventCard";
import HomeMotion from "./HomeMotion";
const categories = [{ name:"Music", label:"Live music", icon:Music2, color:"blue" }, { name:"Culture", label:"Arts & culture", icon:Drama, color:"orange" }, { name:"Sport", label:"Sport", icon:Trophy, color:"green" }, { name:"Food", label:"Food & drink", icon:Utensils, color:"purple" }];
export default function HomePage({ events, preview }: { events: EventItem[]; preview: boolean }) {
  const featured = events.find(e => e.category === "Music") ?? events[0];
  return <PageFrame><main id="main"><HomeMotion/>{preview && <div className="preview-note">Preview catalogue · Payments are not active</div>}
    <section className="wrap home-intro" data-reveal><div className="intro-heading"><div><p className="eyebrow">EVENTS ACROSS NAMIBIA</p><h1>Go out.<br /><span>Feel everything.</span></h1></div><p>Concerts, festivals, sport and culture.<br className="desktop-break" /> Find a date worth keeping.</p></div><SearchForm /></section>
    {featured && <section className="wrap featured-section" aria-label="Featured event" data-reveal><div className="feature-card"><img className="feature-photo" src={preview ? "/images/design1/hero.png" : featured.img} alt={featured.title} fetchPriority="high" /><div className="feature-shade" /><div className="feature-top"><span className="feature-badge">FEATURED</span><span>01 / 01</span></div><div className="feature-content"><div><p className="feature-kicker">{featured.fullDate} <span>·</span> {featured.location}</p><h2>{featured.title}</h2><p>See the venue, schedule and ticket options.</p></div><Link href={`/events/${featured.id}`} className="button white">View event <ArrowUpRight size={19} /></Link></div></div></section>}
    <section className="wrap category-section" aria-label="Explore categories" data-reveal><span className="eyebrow">BROWSE BY MOOD</span><div className="category-grid">{categories.map(c => <Link key={c.name} href={`/events?category=${c.name}`}><span className={`category-icon ${c.color}`}><c.icon size={22} /></span><span>{c.label}</span><ArrowUpRight size={18} /></Link>)}</div></section>
    <section className="wrap home-events" data-reveal><div className="section-heading"><div><p className="eyebrow">COMING UP</p><h2>Events on the calendar.</h2></div><Link className="text-link" href="/events">See all events <ArrowRight size={18} /></Link></div><div className="event-grid">{events.slice(0,4).map(e => <EventCard key={e.id} event={e} />)}</div>{!events.length && <div className="empty-state"><h3>No events published yet.</h3><p>New dates will appear here.</p></div>}</section>
    <section className="city-section" data-reveal><div className="wrap"><div className="section-heading"><div><p className="eyebrow">EXPLORE BY CITY</p><h2>Find something nearby.</h2></div><span className="muted">Three places to start.</span></div><div className="city-grid">{["Windhoek","Swakopmund","Walvis Bay"].map((city,i) => <Link href={`/events?city=${encodeURIComponent(city)}`} key={city}><span className="city-number">0{i+1}</span><MapPin size={20} /><h3>{city}</h3><span>View events <ArrowUpRight size={16} /></span></Link>)}</div></div></section>
    <section className="wrap account-banner" data-reveal><span className="account-banner-icon"><Ticket size={30} /></span><div><p className="eyebrow">YOUR EASY TICKETS ACCOUNT</p><h2>Save events. Find every ticket.</h2><p>Your bookings and QR tickets stay together.</p></div><Link href="/auth/sign-up" className="button primary">Create account <ArrowRight size={18} /></Link></section>
  </main></PageFrame>;
}
