-- Prepared migration. Inspect the existing Easy Tickets schema before applying.
-- Website tables are namespaced to avoid changing the mobile app's tables.
begin;
create table public.website_organisations (id uuid primary key default gen_random_uuid(), name text not null check(length(name) between 2 and 120), created_at timestamptz not null default now());
create table public.website_organiser_members (organisation_id uuid not null references public.website_organisations(id), user_id uuid not null references auth.users(id), role text not null check(role in ('owner','manager')), primary key(organisation_id,user_id));
create index on public.website_organiser_members(user_id);
create table public.website_profiles (user_id uuid primary key references auth.users(id) on delete cascade, full_name text not null check(length(full_name) between 2 and 100), phone text not null default '' check(length(phone)<=30), city text not null default '' check(length(city)<=60));
create table public.website_events (id integer generated by default as identity(start with 1000) primary key, organisation_id uuid not null references public.website_organisations(id), title text not null, starts_at timestamptz not null, published boolean not null default false, payload jsonb not null, created_at timestamptz not null default now());
create index on public.website_events(organisation_id);
create index on public.website_events(starts_at) where published;
create table public.website_saved_events (user_id uuid not null references auth.users(id) on delete cascade, event_id integer not null references public.website_events(id) on delete cascade, primary key(user_id,event_id));
create table public.website_event_staff (event_id integer not null references public.website_events(id) on delete cascade, user_id uuid not null references auth.users(id), primary key(event_id,user_id));
create index on public.website_event_staff(user_id);
alter table public.orders add column user_id uuid references auth.users(id) on delete set null;
create index on public.orders(user_id);
create index on public.orders(event_id,status);
create table public.website_tickets (
 id uuid primary key default gen_random_uuid(), order_id uuid not null references public.orders(id), item_index integer not null, sequence integer not null,
 event_id integer not null, event_name text not null, event_date timestamptz, tier_name text not null, holder_name text not null,
 secret text not null default(replace(gen_random_uuid()::text,'-','')||replace(gen_random_uuid()::text,'-','')),
 status text not null default 'valid' check(status in ('valid','used','void')), checked_in_at timestamptz, checked_in_by uuid references auth.users(id),
 unique(order_id,item_index,sequence)
);
create index on public.website_tickets(event_id,status);

alter table public.website_organisations enable row level security;
alter table public.website_organiser_members enable row level security;
alter table public.website_profiles enable row level security;
alter table public.website_events enable row level security;
alter table public.website_saved_events enable row level security;
alter table public.website_event_staff enable row level security;
alter table public.website_tickets enable row level security;
revoke all on public.website_organisations,public.website_organiser_members,public.website_profiles,public.website_events,public.website_saved_events,public.website_event_staff,public.website_tickets from anon,authenticated;
grant all on public.website_organisations,public.website_organiser_members,public.website_profiles,public.website_events,public.website_saved_events,public.website_event_staff,public.website_tickets to service_role;
grant usage,select on sequence public.website_events_id_seq to service_role;
grant select on public.website_events to anon,authenticated;
grant select on public.website_organisations,public.website_organiser_members,public.website_event_staff to authenticated;
grant select,insert,update on public.website_profiles to authenticated;
grant select,insert,delete on public.website_saved_events to authenticated;
create policy own_membership on public.website_organiser_members for select to authenticated using(user_id=(select auth.uid()));
create policy own_organisation on public.website_organisations for select to authenticated using(exists(select 1 from public.website_organiser_members m where m.organisation_id=id and m.user_id=(select auth.uid())));
create policy published_events on public.website_events for select to anon,authenticated using(published);
create policy managed_events on public.website_events for select to authenticated using(exists(select 1 from public.website_organiser_members m where m.organisation_id=website_events.organisation_id and m.user_id=(select auth.uid())));
create policy own_profile_read on public.website_profiles for select to authenticated using(user_id=(select auth.uid()));
create policy own_profile_insert on public.website_profiles for insert to authenticated with check(user_id=(select auth.uid()));
create policy own_profile_update on public.website_profiles for update to authenticated using(user_id=(select auth.uid())) with check(user_id=(select auth.uid()));
create policy own_saved_read on public.website_saved_events for select to authenticated using(user_id=(select auth.uid()));
create policy own_saved_insert on public.website_saved_events for insert to authenticated with check(user_id=(select auth.uid()));
create policy own_saved_delete on public.website_saved_events for delete to authenticated using(user_id=(select auth.uid()));
create policy own_staff on public.website_event_staff for select to authenticated using(user_id=(select auth.uid()));

-- Organiser event updates and reservation checks take the same row lock.
create function public.save_website_event(p_event_id integer,p_organisation_id uuid,p_payload jsonb,p_published boolean)
returns integer language plpgsql security definer set search_path='' as $$
declare v_id integer; v_start timestamptz; t jsonb; v_sold integer;
begin
 if not exists(select 1 from public.website_organiser_members where organisation_id=p_organisation_id and user_id=auth.uid() and role in ('owner','manager')) then raise exception 'Organiser access required'; end if;
 if coalesce(length(p_payload->>'title'),0) not between 3 and 120 or coalesce(jsonb_array_length(p_payload->'tiers'),0)<>3 or p_payload->>'startsAt' is null then raise exception 'Invalid event'; end if;
 v_start:=replace(replace(p_payload->>'startsAt','/','-'),' ','T')||':00+02:00';
 if v_start<=now() then raise exception 'Event start must be in the future'; end if;
 if p_event_id is null then insert into public.website_events(organisation_id,title,starts_at,payload) values(p_organisation_id,p_payload->>'title',v_start,p_payload) returning id into v_id;
 else select id into v_id from public.website_events where id=p_event_id and organisation_id=p_organisation_id for update; if v_id is null then raise exception 'Event not found'; end if; end if;
 if (select count(distinct x->>'id') from jsonb_array_elements(p_payload->'tiers') x where x->>'id' in ('standard','premium','vip'))<>3 then raise exception 'Invalid ticket types'; end if;
 for t in select value from jsonb_array_elements(p_payload->'tiers') loop
  if t->>'price' is null or t->>'capacity' is null or coalesce(length(t->>'name'),0) not between 1 and 60 or (t->>'price')::numeric<1 or (t->>'price')::numeric>100000 or (t->>'price')::numeric<>trunc((t->>'price')::numeric) or (t->>'capacity')::integer<0 or (t->>'capacity')::integer>1000000 then raise exception 'Invalid price or capacity'; end if;
  select coalesce(sum((i->>'qty')::integer),0) into v_sold from public.orders o cross join lateral jsonb_array_elements(o.items) i where o.event_id=v_id and o.status in ('pending','paid') and i->>'tier'=t->>'id';
  if (t->>'capacity')::integer<v_sold then raise exception 'capacity is below sold and reserved tickets'; end if;
 end loop;
 if not exists(select 1 from jsonb_array_elements(p_payload->'tiers') x where (x->>'capacity')::integer>0) then raise exception 'Set ticket capacity'; end if;
 update public.website_events set title=p_payload->>'title',starts_at=v_start,published=p_published,payload=jsonb_set(p_payload,'{id}',to_jsonb(v_id)) where id=v_id;
 return v_id;
end $$;
revoke execute on function public.save_website_event(integer,uuid,jsonb,boolean) from public,anon;
grant execute on function public.save_website_event(integer,uuid,jsonb,boolean) to authenticated;

-- Prices and capacity are checked again under a lock before creating an order.
create function public.reserve_website_order(p_order jsonb) returns public.orders
language plpgsql security definer set search_path='' as $$
declare e public.website_events; o public.orders; i jsonb; t jsonb; v_used integer; v_total numeric:=0; v_qty integer:=0;
begin
 select * into e from public.website_events where id=(p_order->>'event_id')::integer and published for update;
 if e.id is null or e.starts_at<=now() then raise exception 'Event unavailable'; end if;
 if jsonb_array_length(p_order->'items') not between 1 and 3 then raise exception 'Invalid items'; end if;
 if (select count(distinct x->>'tier') from jsonb_array_elements(p_order->'items') x)<>jsonb_array_length(p_order->'items') then raise exception 'Duplicate ticket types'; end if;
 for i in select value from jsonb_array_elements(p_order->'items') loop
  select value into t from jsonb_array_elements(e.payload->'tiers') where value->>'id'=i->>'tier';
  if t is null or (i->>'qty')::integer not between 1 and 10 then raise exception 'Invalid ticket quantity'; end if;
  if (i->>'unit_price')::numeric<>(t->>'price')::numeric then raise exception 'Ticket prices changed'; end if;
  select coalesce(sum((x->>'qty')::integer),0) into v_used from public.orders old cross join lateral jsonb_array_elements(old.items) x where old.event_id=e.id and old.status in ('pending','paid') and x->>'tier'=i->>'tier';
  if v_used+(i->>'qty')::integer>(t->>'capacity')::integer then raise exception 'Not enough tickets available'; end if;
  v_qty:=v_qty+(i->>'qty')::integer; v_total:=v_total+(i->>'qty')::integer*(t->>'price')::numeric;
 end loop;
 if v_qty>20 or v_total<>(p_order->>'amount')::numeric then raise exception 'Invalid order total'; end if;
 insert into public.orders(ref,user_id,event_id,event_name,event_date,items,amount,currency,buyer_name,buyer_email,buyer_phone)
 values(p_order->>'ref',nullif(p_order->>'user_id','')::uuid,e.id,e.title,e.starts_at,p_order->'items',v_total,p_order->>'currency',p_order->>'buyer_name',p_order->>'buyer_email',p_order->>'buyer_phone') returning * into o;
 return o;
end $$;
revoke execute on function public.reserve_website_order(jsonb) from public,anon,authenticated;
grant execute on function public.reserve_website_order(jsonb) to service_role;

-- Ticket issuance is in the same transaction as the verified paid state.
create function public.issue_website_tickets() returns trigger
language plpgsql security definer set search_path='' as $$
declare i record; n integer;
begin
 if new.status='paid' then
  for i in select value,ordinality from jsonb_array_elements(new.items) with ordinality loop
   for n in 1..(i.value->>'qty')::integer loop
    insert into public.website_tickets(order_id,item_index,sequence,event_id,event_name,event_date,tier_name,holder_name)
    values(new.id,i.ordinality,n,new.event_id,new.event_name,new.event_date,i.value->>'name',new.buyer_name)
    on conflict(order_id,item_index,sequence) do nothing;
   end loop;
  end loop;
 end if;
 return new;
end $$;
revoke execute on function public.issue_website_tickets() from public,anon,authenticated;
create trigger issue_website_tickets after insert or update of status on public.orders for each row execute function public.issue_website_tickets();

create function public.assign_website_event_staff(p_event_id integer,p_email text) returns void
language plpgsql security definer set search_path='' as $$
declare v_user uuid;
begin
 if not exists(select 1 from public.website_events e join public.website_organiser_members m on m.organisation_id=e.organisation_id where e.id=p_event_id and m.user_id=auth.uid() and m.role in ('owner','manager')) then raise exception 'Event manager required'; end if;
 select id into v_user from auth.users where lower(email)=lower(p_email) and email_confirmed_at is not null;
 if v_user is null then raise exception 'Confirmed staff account required'; end if;
 insert into public.website_event_staff(event_id,user_id) values(p_event_id,v_user) on conflict do nothing;
end $$;
revoke execute on function public.assign_website_event_staff(integer,text) from public,anon;
grant execute on function public.assign_website_event_staff(integer,text) to authenticated;

-- Concurrent scanner requests can mark the same ticket used only once.
create function public.check_in_website_ticket(p_ticket_id uuid,p_secret text,p_event_id integer) returns jsonb
language plpgsql security definer set search_path='' as $$
declare t public.website_tickets;
begin
 if not exists(select 1 from public.website_event_staff where event_id=p_event_id and user_id=auth.uid()) then raise exception 'Staff assignment required'; end if;
 select * into t from public.website_tickets where id=p_ticket_id and event_id=p_event_id and secret=p_secret for update;
 if t.id is null then return jsonb_build_object('ok',false,'error','Ticket not valid for this event.'); end if;
 if t.status='used' then return jsonb_build_object('ok',false,'error','This ticket has already been used.'); end if;
 if t.status<>'valid' or not exists(select 1 from public.orders where id=t.order_id and status='paid') then return jsonb_build_object('ok',false,'error','This ticket is not valid.'); end if;
 update public.website_tickets set status='used',checked_in_at=now(),checked_in_by=auth.uid() where id=t.id and status='valid';
 return jsonb_build_object('ok',true,'holder',t.holder_name,'tier',t.tier_name);
end $$;
revoke execute on function public.check_in_website_ticket(uuid,text,integer) from public,anon;
grant execute on function public.check_in_website_ticket(uuid,text,integer) to authenticated;

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('website-event-images','website-event-images',true,8388608,array['image/png','image/jpeg','image/webp']) on conflict(id) do nothing;
-- All uploads use the server route after manager membership verification.

-- Only catalogue data and remaining counts are returned, never buyer data.
create function public.website_catalogue() returns table(payload jsonb)
language sql stable security definer set search_path='' as $$
 select jsonb_set(e.payload,'{tiers}',(
   select jsonb_agg(t || jsonb_build_object('available', greatest(0,(t->>'capacity')::integer - coalesce((
     select sum((i->>'qty')::integer)::integer
     from public.orders o cross join lateral jsonb_array_elements(o.items) i
     where o.event_id=e.id and o.status in ('pending','paid') and i->>'tier'=t->>'id'
   ),0))) order by ordinal)
   from jsonb_array_elements(e.payload->'tiers') with ordinality as types(t,ordinal)
 ))
 from public.website_events e where e.published and e.starts_at > now() order by e.starts_at;
$$;
revoke execute on function public.website_catalogue() from public,anon,authenticated;
grant execute on function public.website_catalogue() to service_role;

commit;
