import Link from "next/link";
import PageFrame from "@/components/site/PageFrame";
export default function HelpPage(){return <PageFrame><main id="main" className="wrap page-content info-page"><p className="eyebrow">HERE TO HELP</p><h1>More going out. Less figuring out.</h1><p className="page-lead">A few things to know about booking with Easy Tickets.</p><div className="faq-list">{[
  ["How do I book?","Find an event, choose your ticket type and quantity, then enter your details. Payment takes place on DPO’s hosted checkout. Your booking is confirmed after payment is verified."],
  ["Do I need an account?","You can book as a guest. Sign in before booking to keep your orders in My tickets. For guest bookings, keep the confirmation link shown after payment."],
  ["What do I show at the entrance?","Open your ticket’s QR code on your phone, or bring a downloaded copy. Every admission has its own ticket. A copied or shared code is still the same ticket and can only be used once."],
  ["Can I add a ticket to Apple or Google Wallet?","Wallet passes are planned. Until they are enabled, use the mobile ticket page or download your ticket. Wallet buttons will appear only when the service is available."],
  ["What if my payment is pending?","Do not pay again until you have checked the status of your original transaction. Keep your booking and DPO references. A pending payment does not yet issue a ticket."],
  ["Can I get a refund or transfer my ticket?","Refund and transfer arrangements depend on the event. Contact the organiser using the details on the event listing. Sharing a ticket copy does not transfer ownership."],
].map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div><h2 id="privacy">Your account information</h2><p>Your profile holds the details you provide. Booking details are used to process your order and validate admission. Your password is handled by Supabase authentication; payment card details are entered on DPO’s payment page.</p><p>Full purchase, refund and privacy policies and the support contact must be supplied by Easy Tickets before public launch.</p><Link href="/account/tickets" className="button secondary">Go to My tickets</Link></main></PageFrame>;}
